backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: public/img
public_folder: /img

collections:
  - name: 'textblock'
    label: 'textblock'
    folder: 'content/textblock'
    format: 'frontmatter'
    create: true
    slug: 'textblock-{{id}}'
    editor:
      preview: true
    fields:
      - { label: 'id', name: 'id', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'show', name: 'show', widget: 'boolean', default: true }
      - { label: 'section', name: 'section', widget: 'string' }
      - { label: 'Bild', name: 'bild', widget: 'image'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'kurse'
    label: 'kurse'
    folder: 'content/kurse'
    format: 'frontmatter'
    create: true
    slug: 'kurse-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'order', name: 'order', widget: 'number' }
      - { label: 'show', name: 'show', widget: 'boolean', default: true }
      - { label: 'overlayed', name: 'overlayed', widget: 'boolean', default: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }